--- 
title: "OHI Country Opportunities"
# title: "Country Opportunities with OHI Global Assessments"
author: "The Ocean Health Index Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ohi-science/country-opportunities-training
description: "This is official training for country opportunities with global Ocean Health Index assessments."
---

# Welcome {#welcome}

-- *This book is under active development* --

This training book will help you interpret Ocean Health Index global assessments and discover opportunities at a country scale. This book covers global assessments conceptually with the OHI framework, and technically with the data included in the global assessment. Discussion will be country-specific: how the information included in the OHI global assessment represents your country. 

By the end of the workshop, we will demonstrate how OHI scores can be recalculated for your country based on input from the workshop discussions. Additionally, we will discuss a plan for further tailoring so that OHI scores better represent your country. 

All the information we cover is available online; this book is a resource to everything we cover, as are the links within. 

**How to use this book**

This book is a guide to interpreting and exploring global assessments for a specific country or territory (of the 220 coastal countries/territories that are scored). The book is written to help guide this interpretation and exporation, and will have specific countries as examples. <!---and is best accompanied with a ---> Each chapter will have the same structure, starting with the Objectives and Resources for the chapter, and ending with examples for a specific country or territory. 
