# Interpret Global Scores {#interpret} 
<!---or interpret framework?--->

```{r interpret, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(htmltools)
```

## Objectives and Resources

This chapter will focus on the conceptual framework of the Ocean Health Index. We will interpret the goals assessed and the scores for the global assessments, and discuss whether all the goals are relevant for the specific country. 

### Objectives

### Resources 

- http://www.oceanhealthindex.org/methodology/goals
- http://ohi-science.org/goals/
- http://www.oceanhealthindex.org/region-scores

----

## Goals Assessed

These are the goals that were assessed

(short, mostly links)

- all 10 
- philosophy
- first mention of global data/ref points (will go deeper)
- first mention pressure/resilience measures (will go deeper)

## Calculating Scores

## Scores and Flowerplots

Interpreting scores (with global average) 

- 1-100
- flower plots



## Discussion: Are all goals relevant here?

Let's start off by looking at [oceanhealthindex.org/region-scores](http://www.oceanhealthindex.org/region-scores) and typing in the country of interest, for example: [Samoa](http://www.oceanhealthindex.org/region-scores/scores/samoa).

- are any goals not assessed (NA)?
- what do their scores mean?

## Discussion: Are all resilience measures relevant here?







